CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS commerce;
CREATE TABLE commerce.users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE,password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES commerce.users(id),expires_at timestamptz NOT NULL);
CREATE INDEX sessions_expiry ON commerce.sessions(expires_at);
CREATE TABLE commerce.organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.memberships(organization_id uuid NOT NULL REFERENCES commerce.organizations(id),user_id uuid NOT NULL REFERENCES commerce.users(id),role text NOT NULL CHECK(role IN ('owner','admin','staff','viewer')),PRIMARY KEY(organization_id,user_id));
CREATE TABLE commerce.merchants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL UNIQUE REFERENCES commerce.organizations(id),display_name text NOT NULL,instagram_handle text,status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','rejected')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE);
CREATE TABLE commerce.products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),category_id uuid REFERENCES commerce.categories(id),title text NOT NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','archived')),embedding vector(1536),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,id));
CREATE TABLE commerce.variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),product_id uuid NOT NULL REFERENCES commerce.products(id),sku text NOT NULL,attributes jsonb NOT NULL DEFAULT '{}',price_minor bigint NOT NULL CHECK(price_minor>=0),currency text NOT NULL DEFAULT 'IRR' CHECK(currency='IRR'),UNIQUE(organization_id,sku),UNIQUE(organization_id,id),FOREIGN KEY(organization_id,product_id) REFERENCES commerce.products(organization_id,id));
CREATE TABLE commerce.inventory(variant_id uuid PRIMARY KEY REFERENCES commerce.variants(id),available integer NOT NULL DEFAULT 0 CHECK(available>=0),reserved integer NOT NULL DEFAULT 0 CHECK(reserved>=0),committed integer NOT NULL DEFAULT 0 CHECK(committed>=0));
CREATE TABLE commerce.stock_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),variant_id uuid NOT NULL REFERENCES commerce.variants(id),kind text NOT NULL CHECK(kind IN ('receive','reserve','release','commit','ship')),quantity integer NOT NULL CHECK(quantity>0),actor_id uuid NOT NULL REFERENCES commerce.users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),buyer_id uuid NOT NULL REFERENCES commerce.users(id),status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','pending_payment','paid','fulfilling','shipped','completed','cancelled','refunded')),amount_minor bigint NOT NULL CHECK(amount_minor>=0),currency text NOT NULL DEFAULT 'IRR' CHECK(currency='IRR'),version integer NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES commerce.orders(id),provider text NOT NULL,provider_reference text UNIQUE,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','succeeded','failed','refunded')),amount_minor bigint NOT NULL CHECK(amount_minor>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.ledger_accounts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),code text NOT NULL,currency text NOT NULL DEFAULT 'IRR' CHECK(currency='IRR'),UNIQUE(organization_id,code));
CREATE TABLE commerce.journals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),reference text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,reference));
CREATE TABLE commerce.ledger_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),journal_id uuid NOT NULL REFERENCES commerce.journals(id),account_id uuid NOT NULL REFERENCES commerce.ledger_accounts(id),debit bigint NOT NULL CHECK(debit>=0),credit bigint NOT NULL CHECK(credit>=0),CHECK((debit>0)<>(credit>0)));
CREATE FUNCTION commerce.check_journal() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE j uuid; n bigint; d numeric; c numeric;
BEGIN
 j:=CASE WHEN TG_TABLE_NAME='journals' THEN NEW.id ELSE NEW.journal_id END;
 SELECT count(*),coalesce(sum(debit),0),coalesce(sum(credit),0) INTO n,d,c FROM commerce.ledger_entries WHERE journal_id=j;
 IF n<2 OR d<>c THEN RAISE EXCEPTION 'Unbalanced journal'; END IF;
 IF EXISTS(SELECT 1 FROM commerce.ledger_entries e JOIN commerce.ledger_accounts a ON a.id=e.account_id JOIN commerce.journals x ON x.id=e.journal_id WHERE x.id=j AND a.organization_id<>x.organization_id) THEN RAISE EXCEPTION 'Cross-tenant journal'; END IF;
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER balanced_journal AFTER INSERT ON commerce.journals DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION commerce.check_journal();
CREATE CONSTRAINT TRIGGER balanced_entries AFTER INSERT ON commerce.ledger_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION commerce.check_journal();
CREATE FUNCTION commerce.immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only table'; END $$;
CREATE TRIGGER immutable_journal BEFORE UPDATE OR DELETE ON commerce.journals FOR EACH ROW EXECUTE FUNCTION commerce.immutable();
CREATE TRIGGER immutable_entries BEFORE UPDATE OR DELETE ON commerce.ledger_entries FOR EACH ROW EXECUTE FUNCTION commerce.immutable();
CREATE TRIGGER immutable_movements BEFORE UPDATE OR DELETE ON commerce.stock_movements FOR EACH ROW EXECUTE FUNCTION commerce.immutable();
CREATE TABLE commerce.outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),topic text NOT NULL,payload jsonb NOT NULL,traceparent text,created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,processed_at timestamptz);
CREATE INDEX outbox_pending ON commerce.outbox(created_at) WHERE published_at IS NULL;
CREATE TABLE commerce.instagram_inbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),digest text NOT NULL UNIQUE,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'received' CHECK(status IN ('received','processed','failed')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE commerce.idempotency(scope text NOT NULL,key text NOT NULL,hash text NOT NULL,response jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(scope,key));
CREATE TABLE commerce.notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES commerce.organizations(id),event_id uuid NOT NULL UNIQUE REFERENCES commerce.outbox(id),kind text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX product_tenant ON commerce.products(organization_id,created_at);
CREATE INDEX orders_tenant ON commerce.orders(organization_id,created_at);
CREATE INDEX movement_variant ON commerce.stock_movements(variant_id,created_at);
